In [1]:
import pandas
import numpy

In [2]:
import pandas as pd
import numpy as np

In [5]:
3+2*4

11

In [6]:
(3+2)/4

1.25

In [7]:
(3+2)^4

1

In [8]:
(3+2)//4

1

In [10]:
type(4//7)

int

In [11]:
a = 11/(-3)
type(a)

float

In [12]:
b = True
type(b)

bool

In [14]:
id = '00223298'
type(id)

str

In [15]:
c = '6.0'
c = float(c)

In [16]:
type(c)

float

In [17]:
d = (-6) < 78
d

True

In [18]:
d = float(d)

In [20]:
type(d)

float

In [35]:
l = [0, "robot", -9, False, 77, 77, 100, "true"]

In [24]:
type(l)

list

In [26]:
t = (0, "robot", -9, False, 77, 77, 100, "true")

In [27]:
type(t)

tuple

In [28]:
s = {0, "robot", -9, False, 77, 77, 100, "true"}

In [29]:
type(s)

set

In [33]:
l[7] = 1

In [36]:
l

[0, 'robot', -9, False, 77, 77, 100, 'true']

In [37]:
e = ['diabetes', 'heart bypass']
e

['diabetes', 'heart bypass']

In [38]:
f = e + ['age', 'weight']

In [39]:
f

['diabetes', 'heart bypass', 'age', 'weight']

In [40]:
e.extend(['age', 'weight'])
e

['diabetes', 'heart bypass', 'age', 'weight']

In [41]:
cities = {'Australia' :['Sydney', 'Melbourne', 'Canberra'],
          'Canada'    :['Toronto', 'Montreal', 'Ottawa'],
          'Germany'   :['Berlin', 'Hamburg', 'Munich'],
          'Japan'     :['Tokyo', 'Osaka', 'Nagoya']}
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya']}

In [42]:
cities['Japan']

['Tokyo', 'Osaka', 'Nagoya']

In [43]:
cities.values()

dict_values([['Sydney', 'Melbourne', 'Canberra'], ['Toronto', 'Montreal', 'Ottawa'], ['Berlin', 'Hamburg', 'Munich'], ['Tokyo', 'Osaka', 'Nagoya']])

In [44]:
cities.keys()

dict_keys(['Australia', 'Canada', 'Germany', 'Japan'])

In [45]:
for k in cities.keys():
    print('key: ', k, '\nvalue: ', cities[k], '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



In [48]:
for k, v in cities.items():
    print('key: ', k, '\nvalue: ', v, '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



In [49]:
cities['Egypt'] = ['Cairo', 'Durban', 'Alexandria']

In [50]:
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Durban', 'Alexandria']}

In [52]:
durban_index = cities['Egypt'].index('Durban')

In [53]:
cities['Egypt'][durban_index] = 'Giza'

In [54]:
print(cities['Egypt'])

['Cairo', 'Giza', 'Alexandria']


In [55]:
del cities['Germany']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

In [56]:
arr = [99,2,65]
arr

[99, 2, 65]

In [57]:
np.log(arr)

array([4.59511985, 0.69314718, 4.17438727])

In [58]:
np.sqrt(arr)

array([9.94987437, 1.41421356, 8.06225775])

In [59]:
np.cos(arr)

array([ 0.03982088, -0.41614684, -0.56245385])

In [60]:
num1 = np.arange(20)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
num1[0:5]

array([0, 1, 2, 3, 4])

In [68]:
num2 = np.arange(20).reshape(5,4)
num2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [110]:
num2[3:5,0:3]

array([[12, 13, 14],
       [16, 17, 18]])

In [103]:
bank = pd.read_csv('bank_data.csv')
bank

age            job  marital  education default  balance housing loan  \
0     30.0     unemployed  married    primary      no   1787.0      no   no   
1     33.0       services  married  secondary      no   4789.0     yes  yes   
2     35.0     management   single   tertiary      no   1350.0     yes   no   
3     30.0     management  married   tertiary      no      NaN     yes  yes   
4     59.0    blue-collar  married  secondary      no      0.0     yes   no   
...    ...            ...      ...        ...     ...      ...     ...  ...   
4516  33.0       services  married  secondary      no   -333.0     yes   no   
4517  57.0  self-employed  married   tertiary     yes  -3313.0     yes  yes   
4518  57.0     technician  married  secondary      no    295.0      no   no   
4519  28.0    blue-collar  married  secondary      no   1137.0      no   no   
4520  44.0   entrepreneur   single   tertiary      no   1136.0     yes  yes   

       contact   day  month  duration  campaign  pdays  previous poutcome   y  \
0     cellular  19.0     10      79.0       1.0   -1.0       0.0  unknown  no   
1     cellular  11.0      5     220.0       1.0  339.0       4.0  failure  no   
2     cellular  16.0      4     185.0       1.0  330.0       1.0  failure  no   
3          NaN   3.0      6     199.0       4.0   -1.0       0.0  unknown  no   
4          NaN   5.0      5     226.0       1.0   -1.0       0.0  unknown  no   
...        ...   ...    ...       ...       ...    ...       ...      ...  ..   
4516  cellular  30.0      7     329.0       5.0   -1.0       0.0  unknown  no   
4517       NaN   9.0      5     153.0       1.0   -1.0       0.0  unknown  no   
4518  cellular  19.0      8     151.0      11.0   -1.0       0.0  unknown  no   
4519  cellular   6.0      2     129.0       4.0  211.0       3.0    other  no   
4520  cellular   3.0      4     345.0       2.0  249.0       7.0    other  no   

      year  
0     2022  
1     2022  
2     2022  
3     2022  
4     2022  
...    ...  
4516  2022  
4517  2022  
4518  2022  
4519  2022  
4520  2022  

[4521 rows x 18 columns]

In [104]:
bank = pd.DataFrame(bank)

In [105]:
age_series = bank['age']

In [106]:
type(age_series)

pandas.core.series.Series

In [107]:
selected_columns_df = bank[['job', 'education', 'balance']]

In [108]:
type(selected_columns_df)

pandas.core.frame.DataFrame

In [114]:
bank.iloc[-7:, :5]

age            job  marital  education default
4514  38.0    blue-collar  married  secondary      no
4515  32.0       services   single  secondary      no
4516  33.0       services  married  secondary      no
4517  57.0  self-employed  married   tertiary     yes
4518  57.0     technician  married  secondary      no
4519  28.0    blue-collar  married  secondary      no
4520  44.0   entrepreneur   single   tertiary      no

In [118]:
bank['contact_date'] = bank['year'].astype(str)+'-'+bank['month'].astype(str)+'-'+bank['day'].astype(int).astype(str)
bank['contact_date']

0       2022-10-19
1        2022-5-11
2        2022-4-16
3         2022-6-3
4         2022-5-5
           ...    
4516     2022-7-30
4517      2022-5-9
4518     2022-8-19
4519      2022-2-6
4520      2022-4-3
Name: contact_date, Length: 4521, dtype: object

In [123]:
bank['contact_date'] = pd.to_datetime(bank['contact_date'])
bank['contact_date']

0      2022-10-19
1      2022-05-11
2      2022-04-16
3      2022-06-03
4      2022-05-05
          ...    
4516   2022-07-30
4517   2022-05-09
4518   2022-08-19
4519   2022-02-06
4520   2022-04-03
Name: contact_date, Length: 4521, dtype: datetime64[ns]

In [124]:
import warnings
warnings.filterwarnings("ignore")

In [139]:
hc = pd.read_csv('hc_train.csv')
hc

Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital          Department Ward_Type  \
0                                      3          gynecology         R   
1                                      4          gynecology         Q   
2                                      4          gynecology         S   
3                                      2          anesthesia         S   
4                                      3          gynecology         R   
...                                  ...                 ...       ...   
51233                                  3          gynecology         Q   
51234                                  4          gynecology         Q   
51235                                  3          gynecology         S   
51236                                  4          gynecology         R   
51237                                  2  TB & Chest disease         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme                      4  51-6

In [140]:
hc.loc[0:4]

Unnamed: 0  case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0      119967   119968             27                  a                   7   
1       92433    92434              6                  a                   6   
2      132258   132259             16                  c                   3   
3      168439   168440             23                  a                   6   
4       82100    82101             25                  e                   1   

  Hospital_region_code  Available Extra Rooms in Hospital  Department  \
0                    Y                                  3  gynecology   
1                    X                                  4  gynecology   
2                    Z                                  4  gynecology   
3                    X                                  2  anesthesia   
4                    X                                  3  gynecology   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  C        2.0      11389                8.0   
1         Q                  F        1.0      12522                2.0   
2         S                  A        3.0     119556                8.0   
3         S                  F        3.0     107177                8.0   
4         R                  E        3.0      64508               13.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency               Minor                      2  11-20   
1         Emergency             Extreme                      4  31-40   
2            Trauma            Moderate                      6  71-80   
3            Urgent             Extreme                      2  71-80   
4            Trauma            Moderate                      3  61-70   

   Admission_Deposit                Stay  
0             5072.0               21-30  
1             3585.0               21-30  
2             4013.0  More than 100 Days  
3             5160.0               21-30  
4             4099.0               21-30

In [143]:
hc['Department'] = hc['Department'].str.upper()

In [144]:
hc['Department'] = hc['Department'].replace('TB & Chest disease', 'Tuberculosis & Chest')

In [145]:
hc['Department'].unique()

array(['GYNECOLOGY', 'ANESTHESIA', 'RADIOTHERAPY', 'SURGERY',
       'TB & CHEST DISEASE'], dtype=object)

In [146]:
map_dict = {'Extreme': '3rd degree', 'Moderate': '2nd degree', 'Minor': '1st degree'}
hc['Severity of Illness'] = hc['Severity of Illness'].map(map_dict)

In [150]:
hc.rename(columns=str.lower)

unnamed: 0  case_id  hospital_code hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital          department ward_type  \
0                                      3          GYNECOLOGY         R   
1                                      4          GYNECOLOGY         Q   
2                                      4          GYNECOLOGY         S   
3                                      2          ANESTHESIA         S   
4                                      3          GYNECOLOGY         R   
...                                  ...                 ...       ...   
51233                                  3          GYNECOLOGY         Q   
51234                                  4          GYNECOLOGY         Q   
51235                                  3          GYNECOLOGY         S   
51236                                  4          GYNECOLOGY         R   
51237                                  2  TB & CHEST DISEASE         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission severity of illness  visitors with patient    age  \
0             Emergency          1st degree                      2  11-20   
1             Emergency          3rd degree                      4  31-40   
2                Trauma          2nd degree                      6  71-80   
3                Urgent          3rd degree                      2  71-80   
4                Trauma          2nd degree                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma          1st degree                      2  21-30   
51234         Emergency          2nd degree                      2  51-60   
51235         Emergency          2nd degree                     10  51-60   
51236            Trauma          1st degree                      2  21-30   
51237            Trauma          3rd degree                      4  51-6

In [157]:
col_dict = {'severity of illness': 'Severity', 'case_id': 'ID'}
hc.rename(columns = (col_dict))

unnamed: 0      ID  hospital_code hospital_type_code  \
0          119967  119968             27                  a   
1           92433   92434              6                  a   
2          132258  132259             16                  c   
3          168439  168440             23                  a   
4           82100   82101             25                  e   
...           ...     ...            ...                ...   
51233      289419  289420             10                  e   
51234      285283  285284             11                  b   
51235       79117   79118              9                  d   
51236      128901  128902             23                  a   
51237      210970  210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital          department ward_type  \
0                                      3          GYNECOLOGY         R   
1                                      4          GYNECOLOGY         Q   
2                                      4          GYNECOLOGY         S   
3                                      2          ANESTHESIA         S   
4                                      3          GYNECOLOGY         R   
...                                  ...                 ...       ...   
51233                                  3          GYNECOLOGY         Q   
51234                                  4          GYNECOLOGY         Q   
51235                                  3          GYNECOLOGY         S   
51236                                  4          GYNECOLOGY         R   
51237                                  2  TB & CHEST DISEASE         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission    Severity  visitors with patient    age  \
0             Emergency  1st degree                      2  11-20   
1             Emergency  3rd degree                      4  31-40   
2                Trauma  2nd degree                      6  71-80   
3                Urgent  3rd degree                      2  71-80   
4                Trauma  2nd degree                      3  61-70   
...                 ...         ...                    ...    ...   
51233            Trauma  1st degree                      2  21-30   
51234         Emergency  2nd degree                      2  51-60   
51235         Emergency  2nd degree                     10  51-60   
51236            Trauma  1st degree                      2  21-30   
51237            Trauma  3rd degree                      4  51-60   

       admission_deposit                stay  
0                 5072.0               21-30  
1       

In [162]:
hc['case_id'].max()

318438

In [165]:
bins = [0, 100001, 200001, np.inf]
categories = ['old case', 'recent case', 'new case']
binning_case_id= hc['case_id']
group = pd.cut(binning_case_id, bins, labels=categories)
group

0        recent case
1           old case
2        recent case
3        recent case
4           old case
            ...     
51233       new case
51234       new case
51235       old case
51236    recent case
51237       new case
Name: case_id, Length: 51238, dtype: category
Categories (3, object): ['old case' < 'recent case' < 'new case']

In [169]:
group_equ = pd.cut(binning_case_id, 3, precision=4)
group_equ

0        (106146.6667, 212292.3333]
1           (-317.437, 106146.6667]
2        (106146.6667, 212292.3333]
3        (106146.6667, 212292.3333]
4           (-317.437, 106146.6667]
                    ...            
51233       (212292.3333, 318438.0]
51234       (212292.3333, 318438.0]
51235       (-317.437, 106146.6667]
51236    (106146.6667, 212292.3333]
51237    (106146.6667, 212292.3333]
Name: case_id, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(-317.437, 106146.6667] < (106146.6667, 212292.3333] < (212292.3333, 318438.0]]

In [170]:
group_qua = pd.qcut(binning_case_id, 3, precision=2)
group_qua

0        (106907.0, 212651.0]
1            (0.99, 106907.0]
2        (106907.0, 212651.0]
3        (106907.0, 212651.0]
4            (0.99, 106907.0]
                 ...         
51233    (212651.0, 318438.0]
51234    (212651.0, 318438.0]
51235        (0.99, 106907.0]
51236    (106907.0, 212651.0]
51237    (106907.0, 212651.0]
Name: case_id, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(0.99, 106907.0] < (106907.0, 212651.0] < (212651.0, 318438.0]]

In [172]:
hc.sample(10)

unnamed: 0  case_id  hospital_code hospital_type_code  \
42924      210287   210288              6                  a   
20061      132155   132156             10                  e   
14335      239680   239681             26                  b   
29737        7277     7278             19                  a   
5384        16288    16289             29                  a   
6377       286862   286863             12                  a   
49566      284395   284396             22                  g   
13241      263347   263348             23                  a   
20711      176964   176965             10                  e   
41173      290667   290668             10                  e   

       city_code_hospital hospital_region_code  \
42924                   6                    X   
20061                   1                    X   
14335                   2                    Y   
29737                   7                    Y   
5384                    4                    X   
6377                    9                    Y   
49566                   9                    Y   
13241                   6                    X   
20711                   1                    X   
41173                   1                    X   

       available extra rooms in hospital          department ward_type  \
42924                                  3          GYNECOLOGY         R   
20061                                  3          GYNECOLOGY         R   
14335                                  4          GYNECOLOGY         R   
29737                                  3          GYNECOLOGY         S   
5384                                   4          GYNECOLOGY         R   
6377                                   4          GYNECOLOGY         S   
49566                                  2          GYNECOLOGY         S   
13241                                  1          ANESTHESIA         R   
20711                                  2          GYNECOLOGY         Q   
41173                                  2  TB & CHEST DISEASE         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
42924                  F        2.0      77636                4.0   
20061                  E        2.0      75814                5.0   
14335                  D        2.0      23364                4.0   
29737                  C        3.0      38662                8.0   
5384                   F        4.0     101042                2.0   
6377                   B        3.0     119265               23.0   
49566                  B        2.0      21440               11.0   
13241                  F        3.0       6138                8.0   
20711                  E        3.0      23265                8.0   
41173                  E        2.0     111420               20.0   

      type of admission severity of illness  visitors with patient    age  \
42924            Trauma          2nd degree                      3  51-60   
20061            Trauma          2nd degree                      2  31-40   
14335            Trauma          2nd degree                      2  41-50   
29737         Emergency          1st degree                      2  21-30   
5384             Trauma          3rd degree                      2  61-70   
6377             Trauma          1st degree                      2  31-40   
49566         Emergency          2nd degree                      4  41-50   
13241            Trauma          2nd degree                      6  41-50   
20711            Trauma          3rd degree                      2  71-80   
41173         Emergency          3rd degree                      2  11-20   

       admission_deposit   stay  
42924             5419.0   0-10  
20061             4948.0  41-50  
14335             4883.0  41-50  
29737             6686.0  31-40  
5384              7097.0  31-40  
6377              4689.0  11-20  
49566             3774.0  31-40  
13241             3820.0  51-60  
20711             4404

In [179]:
hc.iloc[:, 12].sample(50, replace=True)

46014    16.0
35826     8.0
31343     5.0
14045     1.0
25724    15.0
18972     8.0
15261    12.0
50486     1.0
5307      7.0
5090      7.0
42091     8.0
13731     9.0
8930      8.0
18631     8.0
24004     8.0
51042    16.0
40282     2.0
39446     8.0
23779     NaN
45576    23.0
14141     9.0
39860     8.0
16036     8.0
10566     8.0
6541      8.0
5956      2.0
7752     11.0
48980     8.0
16046     2.0
42913     9.0
5487      8.0
19547     4.0
6347      8.0
8991      9.0
30524    21.0
46153     8.0
38681     8.0
45277     2.0
31135     7.0
29946     8.0
10297     2.0
39047     8.0
6980      8.0
41995     2.0
43789     8.0
14191    12.0
29724    10.0
26728     7.0
25069     8.0
43191     8.0
Name: city_code_patient, dtype: float64